name: ci
on:
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Use Node.js v22.5.1
        uses: actions/setup-node@v3
        with:
          node-version: v22.5.1

      - name: Install NPM
        run: npm install

      - name: Buils
        run: npm run build

      - name: Run tests
        run: npm run test
      # - name: SonarCloud Scan
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}